//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRental.Data.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Release { get; set; }
        public string Director { get; set; }
        public string Language { get; set; }
        public string Category { get; set; }
        public string Version { get; set; }
    }
}
